### ISSUE TITLE
Windows下一直提示链接失败，但网页和webdav都是可以正常访问的

### ISSUE THREAD

**Issue by AkimioJR** [xtxt19931207/emby-alist#1]
修改位置：
```
# 输入WebDAV地址、用户名和密码
webdav_url = 'al.chirmyram.com:443/dav/ani'#alist webdav 地址
save_mulu='C:\\Users\\xxxx\\OneDrive\\桌面\\webdav'#输出路径
username = 'alist'#用户名
password = 'alist'#密码
```
报错：
```
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
连接失败，1秒后重试...
Traceback (most recent call last):
  File "C:\Users\xxxx\OneDrive\桌面\webdav.py", line 46, in <module>
    l_0=list_files(webdav_url, username, password)[0]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\OneDrive\桌面\webdav.py", line 30, in list_files
    for file in files[1:]:
                ^^^^^
UnboundLocalError: cannot access local variable 'files' where it is not associated with a value
```

**Comment by AkimioJR** [comment]
难道是只能填写ipv4地址并且只能http访问？

**Comment by xtxt19931207** [comment]
链接按下面格式写试试：
webdav_url = 'https://al.chirmyram.com/dav/ani/'
save_mulu='C:/Users/xxxx/OneDriv/桌面/webdav/'

**Comment by AkimioJR** [comment]
地址不能填`\`，会被python当做转义符，应该填两个反斜杠，我等会试试加个https吧

**Comment by xtxt19931207** [comment]
> 地址不能填`\`，会被python当做转义符，应该填两个反斜杠，我等会试试加个https吧

注意我斜杆的方向，按我写的方向没问题，我自己用的也是ipv6地址，还有你这个网站能用浏览器正常打开吗？这个程序也是基于浏览器的

**Comment by AkimioJR** [comment]
windows的路径地址确实是反斜杠，正斜杠是linux，网址访问是正常的

**Comment by AkimioJR** [comment]
加上https后可以下载，但是对多集的动漫好像有点问题，我这边没办法下载多集动漫，只有一集一集的电影

**Comment by AkimioJR** [comment]
举个例子：
```
webdav地址
├── A
│   ├── Season 1
│   │   ├── A S01E01.mp4
│   │   ├── A S01E02.mp4
│   │   ├── A S01E03.mp4
│   │   └── A S01E04.mp4
│   └── Season 2
│       ├── A S02E01.mp4
│       ├── A S02E02.mp4
│       ├── A S02E03.mp4
│       └── A S02E04.mp4
├── B
│   └─── B .mp4
```
这个样子的话`A`就识别不到`B`就正常

**Comment by windmzx** [comment]
> 举个例子：
> 
> ```
> webdav地址
> ├── A
> │   ├── Season 1
> │   │   ├── A S01E01.mp4
> │   │   ├── A S01E02.mp4
> │   │   ├── A S01E03.mp4
> │   │   └── A S01E04.mp4
> │   └── Season 2
> │       ├── A S02E01.mp4
> │       ├── A S02E02.mp4
> │       ├── A S02E03.mp4
> │       └── A S02E04.mp4
> ├── B
> │   └─── B .mp4
> ```
> 
> 这个样子的话`A`就识别不到`B`就正常

确实是 只能识别单层目录
